<a href="https://colab.research.google.com/github/BENMEZIAN/Great-Learning-tutorials/blob/main/NumPy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Introduction to NumPy

In [ ]:
arr1 = np.array([1,2,3,4,5,6]) # one dimensional array
arr2 = np.array([[1,2,3],[4,5,6]]) # two dimensional array
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # three dimensional array
arr4 = np.zeros((3,3)) # zeros array
arr5 = np.ones((3,3)) # ones array
arr6 = np.empty((3,3)) # empty array
arr7 = np.full((3,3),7) # full array
arr8 = np.arange(0,10,2) # arange array
arr9 = np.linspace(0,10,5) # linspace array
arr10 = np.random.rand(3,3) # random array

print("One dimensional array :",arr1)
print("Two dimensional array :",arr2)
print("Three dimensional array :\n",arr3)
print("Zeros array :\n",arr4)
print("Ones array :\n",arr5)
print("Empty array :\n",arr6)
print("Full array :\n",arr7)
print("Arange array :",arr8)
print("Linspace array :",arr9)
print("Random array :",arr10)

One dimensional array : [1 2 3 4 5 6]
Two dimensional array : [[1 2 3]
 [4 5 6]]
Three dimensional array :
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Zeros array :
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones array :
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Empty array :
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Full array :
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Arange array : [0 2 4 6 8]
Linspace array : [ 0.   2.5  5.   7.5 10. ]
Random array : [[0.782371   0.48634357 0.89749081]
 [0.93063836 0.85543841 0.12555732]
 [0.66178587 0.48659461 0.5638435 ]]


# NumPy Operations

In [ ]:
data1 = np.array([1,2,3,4,5,6])
data2 = np.array([7,8,9,10,11,12])
# arr2 = np.array([[1,2,3],[4,5,6]]) # two dimensional array

print("Data1 :",data1)
print("Data2 :",data2)

# Shape
print("Shape of arr1 :",data1.shape)
print("Shape of arr2 :",data2.shape)

# Join array
data_concat = np.concatenate((data1,data2))
print("Concatenated array :",data_concat)

# vstack, hstack, columns_stack functions
data_vstack = np.vstack((data1,data2))
data_hstack = np.hstack((data1,data2))
data_columns_stack = np.column_stack((data1,data2))

print("Vertical stack :\n",data_vstack)
print("Horizontal stack :\n",data_hstack)
print("Columns stack :\n",data_columns_stack)

# intercet1d and setdiff
data_intercet = np.intersect1d(data1,data2)
data_setdiff = np.setdiff1d(data1,data2)
print("Intersection :",data_intercet) # there are no common elements
print("Set difference :",data_setdiff) # only elements in data1

Data1 : [1 2 3 4 5 6]
Data2 : [ 7  8  9 10 11 12]
Shape of arr1 : (6,)
Shape of arr2 : (6,)
Concatenated array : [ 1  2  3  4  5  6  7  8  9 10 11 12]
Vertical stack :
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Horizontal stack :
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Columns stack :
 [[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]
Intersection : []
Set difference : [1 2 3 4 5 6]


# NumPy Mathematics

In [53]:
# np.sum
array1 = np.array([1,2,3,4,5,6])
array2 = np.array([7,8,9,10,11,12])
print("-----------------------------------")
sum = np.sum(array1)
sum_axis_0 = np.sum([array1,array2],axis=0)
sum_axis_1 = np.sum([array1,array2],axis=1)

print("Sum :",sum)
print("Sum axis 0 :",sum_axis_0) # by columns
print("Sum axis 1 :",sum_axis_1) # by rows

# np.mean
mean = np.mean(array1)
mean_axis_0 = np.mean([array1,array2],axis=0)
mean_axis_1 = np.mean([array1,array2],axis=1)

print("Mean :",mean)
print("Mean axis 0 :",mean_axis_0) # by columns
print("Mean axis 1 :",mean_axis_1) # by rows

# np.median
median = np.median(array1)
median_axis_0 = np.median([array1,array2],axis=0)
median_axis_1 = np.median([array1,array2],axis=1)

print("Median :",median)
print("Median axis 0 :",median_axis_0) # by columns
print("Median axis 1 :",median_axis_1) # by rows

# np.std
std = np.std(array1)
std_axis_0 = np.std([array1,array2],axis=0)
std_axis_1 = np.std([array1,array2],axis=1)

print("Standard deviation :",std)
print("Standard deviation axis 0 :",std_axis_0) # by columns
print("Standard deviation axis 1 :",std_axis_1) # by rows

# basic addition, multiplication, division, substraction on these 2 declared arrays
print("-----------------------------------")
print("Addition :",array1+array2)
print("Multiplication :",array1*array2)
print("Division :",array1/array2)
print("Substraction :",array1-array2)
print("-----------------------------------")

-----------------------------------
Sum : 21
Sum axis 0 : [ 8 10 12 14 16 18]
Sum axis 1 : [21 57]
Mean : 3.5
Mean axis 0 : [4. 5. 6. 7. 8. 9.]
Mean axis 1 : [3.5 9.5]
Median : 3.5
Median axis 0 : [4. 5. 6. 7. 8. 9.]
Median axis 1 : [3.5 9.5]
Standard deviation : 1.707825127659933
Standard deviation axis 0 : [3. 3. 3. 3. 3. 3.]
Standard deviation axis 1 : [1.70782513 1.70782513]
-----------------------------------
Addition : [ 8 10 12 14 16 18]
Multiplication : [ 7 16 27 40 55 72]
Division : [0.14285714 0.25       0.33333333 0.4        0.45454545 0.5       ]
Substraction : [-6 -6 -6 -6 -6 -6]
-----------------------------------


# NumPy Matrix

In [76]:
# NumPy matrix
matrix1 = np.matrix([[1,2,3],[4,5,6]])
matrix2 = np.matrix([[7,8,9],[10,11,12]])
square_matrix = np.matrix([[1, 2], [3, 4]])

print("Matrix 1 :\n",matrix1)
print("Matrix 2 :\n",matrix2)

# Access matrix elements
print("Matrix 1 element 0,0 :",matrix1[0,0])
print("Matrix 1 element 0,1 :",matrix1[0,1])
print("Matrix 1 element 0,0 to 1,1 :",matrix1[0:2,0:2]) # 2 are excluded

# transpose
print("Transpose of matrix 1 :\n",np.transpose(matrix1))
print("Transpose of matrix 2 :\n",np.transpose(matrix2))

# Dot product
print("Dot product of matrix 1 and matrix 2 :\n",np.dot(matrix1, np.transpose(matrix2)))

# Inverse
print("Square matrix :\n", square_matrix)
print("Inverse of square matrix :\n", np.linalg.inv(square_matrix))

Matrix 1 :
 [[1 2 3]
 [4 5 6]]
Matrix 2 :
 [[ 7  8  9]
 [10 11 12]]
Matrix 1 element 0,0 : 1
Matrix 1 element 0,1 : 2
Matrix 1 element 0,0 to 1,1 : [[1 2]
 [4 5]]
Transpose of matrix 1 :
 [[1 4]
 [2 5]
 [3 6]]
Transpose of matrix 2 :
 [[ 7 10]
 [ 8 11]
 [ 9 12]]
Dot product of matrix 1 and matrix 2 :
 [[ 50  68]
 [122 167]]
Square matrix :
 [[1 2]
 [3 4]]
Inverse of square matrix :
 [[-2.   1. ]
 [ 1.5 -0.5]]
